### ISSUE TITLE
安装脚本存在工作异常的可能

### ISSUE THREAD

**Issue by WorldMoZara** [toknife/toknife.github.io#6]
服务器上放着的公钥是 armored 的，在我这里存在导入失败的情况。
这时候我不得不用 `gpg --dearmor purofle.gpg.key` 来将其转化成常规的 gpg 文件，然后再导入。

**Comment by purofle** [comment]
![Screenshot_20210102_093825](https://user-images.githubusercontent.com/37149302/103449102-4a6c6300-4cde-11eb-8525-edf657e6005c.jpg)

这是...版本问题？

**Comment by WorldMoZara** [comment]
然而通过 `apt-key` 添加密钥已不被推荐。  
推荐的办法是将二进制GPG密钥文件放到 `$PREFIX/etc/apt/trusted.gpg.d/` 中。
